### ISSUE TITLE
Missing repeater gun

### ISSUE THREAD

**Issue by Deployabledrone** [nkrisztian89/interstellar-armada#410]
The new small repeater gun is not found in the Interstellar-Armada Editor.

**Comment by nkrisztian89** [comment]
The new version is still work in progress. The files for the repeater are already uploaded here in the repository, but it will only show up in the editor when I make a new release. The current release is still last September's update:
https://github.com/nkrisztian89/interstellar-armada/releases
I have a couple of things to finish for this release still, but I am getting there, should be released this month.

**Comment by Deployabledrone** [comment]
Understood, thank you.
